import 'package:core_tools/log_utils.dart';
import 'package:flutter/material.dart';

import '../project/entity/test_entity.dart';
import '../project/http/core/hi_net.dart';
import '../project/http/request/test_request.dart';

class ClickButtonDemo extends StatefulWidget {
  const ClickButtonDemo({Key? key}) : super(key: key);

  @override
  State<ClickButtonDemo> createState() => _ClickButtonDemoState();
}

class _ClickButtonDemoState extends State<ClickButtonDemo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("ClickButtonDemo"),
        elevation: 0.0,
      ),
      body: Container(
        padding: EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Stack(
              alignment: Alignment.topLeft, //对齐方式
              children: [
                Padding(
                  padding: EdgeInsets.fromLTRB(0, 10, 10, 0),
                  child: SizedBox(
                    width: 100.0,
                    height: 100.0,
                    child: Container(
                      alignment: Alignment(0.0, 0.0),
                      decoration: BoxDecoration(
                        color: Color.fromRGBO(3, 54, 255, 1.0),
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                    ),
                  ),
                ),
                SizedBox(
                  width: 200.0,
                  height: 30.0,
                  child: GestureDetector(
                    //子 widget 可点击控件
                    onTap: clickButton,
                    child: Container(
                      decoration: BoxDecoration(
                          color: Color.fromRGBO(3, 54, 255, 1.0),
                          shape: BoxShape.circle,
                          gradient: RadialGradient(//镜像渐变
                              colors: [Colors.green, Colors.green])),
                      child: Icon(Icons.add, color: Colors.white, size: 32.0),
                    ),
                  ),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }

  // void clickButton() {
  //   showToast(msg: "点击了按钮");
  // }

// void clickButton() {
//   HiCache.getInstance().setString(GlobalConstant.userName, "田宇11111");
//   HiCache.getInstance().setString(GlobalConstant.userName, "田宇");
//   HiCache.getInstance().setInt(GlobalConstant.userAge, 20);
//
//   var name = HiCache.getInstance()
//       .get<String>(GlobalConstant.userName); //指定泛型为 String
//   var age =
//       HiCache.getInstance().get(GlobalConstant.userAge); //不指定泛型 Int T 自动推断
//
//   debugPrint("睚眦 => name $name age $age");
// }

  void clickButton() async {
    var result = await HiNet.getInstance().fire(TestRequest());
    var entity = Autogenerated.fromJson(result);
    LogUtils.d(entity.data?.first.desc ?? "", tag: "desc");
  }
}
